img_num: 8054
feature_dim: 128
ori_labels: 'datalist/CARS_0.5noised_train.csv'
#ori_labels: '/mnt/lustre/hukun/yuzhipeng/NoiseFree/noisefreemetriclearing/datalistBT_NMI0.8/CARS_0.5noised_train.csv'
#pretrain_feat: '/mnt/lustre/yuzhipeng/workspace/Ranking-based-Instance-Selection/features/CARS_0.5noised_train_PRISM.npz'
#pretrain_feat: '/mnt/lustre/yuzhipeng/workspace/Ranking-based-Instance-Selection/features/CARS_0.5noised_train_PRISM_BTCLEAN0.2.npz'
#pretrain_feat: '/mnt/lustre/hukun/yuzhipeng/NoiseFree/Ranking-based-Instance-Selection/features/CARS_0.5noised_train_PRISM_BTCLEANiNMI0.83_0.2.npz'
#pretrain_feat: '/mnt/lustre/hukun/yuzhipeng/NoiseFree/Ranking-based-Instance-Selection/features/CARS_0.5noised_train_PRISM.npz'
IA_num: 2
momentum: 0.9
bt: True
tb: True
port: 5870
IA_thres_mode: fixed
IA_thres_value: 0.6
adapt_threshold: True
adapt_range: 0.5
num_classes_pos: 98
num_classes_nonneg: 98
log_path: 'server_log/'
